version: "3.7"

services:
  database:
      image: mdillon/postgis:11
      volumes:
        - delever_pgdata:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=mb_corporate_service
      logging:
        driver: ${LOGGING_DRIVER:-json-file}
      ports:
        - "5434:5432"

volumes:
  delever_pgdata:
